
project_id = "The Content of supabase/config.toml"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[functions]
[functions.voice-to-text]
verify_jwt = true

[functions.llama-chat]
verify_jwt = true
