// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrqzirobmvebubvwwpiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycXppcm9ibXZlYnVidnd3cGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDg4NDIsImV4cCI6MjA2MDEyNDg0Mn0._7giET1DnAajTBKcWUR1HMCQPAul4h7O5PoLzYHF5r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);